export const SomePosts = [
    {
        Username:'IlJack',
        Text:'eoewjhfouwehfeouwhfweiufhwiuehfweophwefhwofwefhweiufhewue',
        imgSrc:"http://placekitten.com/g/360/360"
    },
    {
        Username:'IlJack',
        Text:'eoewjhfouwehfeouwhfweiufhwiuehfweophwefhwofwefhweiufhewu',
        imgSrc:"http://placekitten.com/g/360/360"
    },
    {
        Username:'IlJack',
        Text:'eoewjhfouwehfeouwhfweiufhwiuehfweophwefhwofwefhweiufhewu',
        imgSrc:"http://placekitten.com/g/360/360"
    },
    {
        Username:'IlJack',
        Text:'eoewjhfouwehfeouwhfweiufhwiuehfweophwefhwofwefhweiufhewu',
        imgSrc:"http://placekitten.com/g/360/360"
    }
]